pingme/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('user/', include('user.urls'))
]

if settings.DEBUG:  # Чтобы медиафайлы работали в режиме отладки
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from .views import *

app_name = "user"

urlpatterns = [
    path('register/', RegisterUser.as_view(), name='register_user'),
    path('profile/',  ProfileUser.as_view(), name='profile_user'),
    path('profile/edit/', EditUser.as_view(), name='edit_user'),
    path('login/', LoginUser.as_view(), name='login_user')
    
]

user/models.py
import random
import string
from django.db import models
from django.contrib.auth.models import AbstractUser



def user_directory_path(instance, filename):
    return f'user_{instance.id}/profile_pictures/{filename}'


class CustomUser(AbstractUser):
    profile_picture = models.ImageField(upload_to=user_directory_path, blank=True, null=True)
    telegram_id = models.BigIntegerField(unique=True, blank=True, null=True)
    telegram_confirmation_code = models.CharField(max_length=10, blank=True, null=True)
    email = models.EmailField(unique=True)
    
    def __str__(self):
        return self.username
    
    
    def generate_random_string(self, length=10, chars=string.ascii_letters + string.digits):
        """Генерирует случайную строку заданной длины"""
        return ''.join(random.choices(chars, k=length))
    
    def generate_confirmation_code(self):
        """Метод для генерации уникального кода подтверждения."""
        code = self.generate_random_string()
        while CustomUser.objects.filter(telegram_confirmation_code=code).exists():
            code = self.generate_random_string()
        return code
        
    def save(self, *args, **kwargs):
        if not self.telegram_confirmation_code:
            self.telegram_confirmation_code = self.generate_confirmation_code()
        super().save(*args, **kwargs)
        

user/forms.py
from .models import CustomUser
from django.contrib.auth.forms import UserCreationForm
from django import forms

class RegistrationForm(UserCreationForm):
    
    """
    
    def clean_email
    Сначала получается email введённый пользователем 
    Идёт проверка 
    
    CustomUser.objects.filter(email=email)
    Ищутся все объекты модели CustomUser, у которых поле email равно значению переменной email, возвращается QuerySet
    
    exclude(id=self.instance.id)
    Фильтрует QuerySet исключая объекты соответствующие условию(id=self.instance.id)
    self.instance - текущий объект с которым работает форма
    
    .exists() - Проверяет есть ли в бд объект, который соответствует тому, что написано до
    Если есть совпадение, то вернётся True
    
    """
    
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'first_name', 'last_name']
        widgets = {
            'username' : forms.TextInput(attrs={'class': 'form-control'}),
            'email' : forms.EmailInput(attrs={'class': 'form-control'}),
            'first_name' : forms.TextInput(attrs={'class': 'form-control'}),
            'last_name' : forms.TextInput(attrs={'class': 'form-control'}),
        }
        help_texts = {
            'username': '',
        }
    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if CustomUser.objects.filter(email=email).exclude(id=self.instance.id).exists():
            raise forms.ValidationError('Данный email уже зарегистрирован')
        return email


class EditUserForm(forms.ModelForm):
    
    """
    profile_picture - не обязательное поле, т.к. не всем нужно фото
    
    """
    
    profile_picture = forms.ImageField(required=False)
    class Meta:
        model = CustomUser
        fields = ['profile_picture', 'username', 'first_name', 'last_name']
        
class ProfileUserForm(forms.ModelForm):
    
    """
    exclude исключаем telegram_confirmation_code, дабы у пользователя всё работало коректно
    
    """
    
    class Meta:
        model = CustomUser
        exclude = ['telegram_confirmation_code', ]
        

user/views.py
from django.urls import reverse_lazy
from django.views.generic import FormView, CreateView, UpdateView
from django.contrib.auth import login
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin

from user.forms import RegistrationForm, EditUserForm, ProfileUserForm
from user.models import CustomUser


class RegisterUser(CreateView):
    template_name = 'user/register_user.html'
    form_class = RegistrationForm
    success_url = reverse_lazy('user:login_user')
    
    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return super().form_valid(form)
    

class ProfileUser(LoginRequiredMixin, FormView):
    template_name = 'user/profile_user.html'
    form_class = ProfileUserForm
    
    def get_object(self, queryset = None):
        return super().get_object(queryset)


class LoginUser(LoginView):
    form_class = AuthenticationForm
    template_name = 'user/login_user.html'
    
    def get_success_url(self):
        return self.get_redirect_url() or reverse_lazy('user:profile_user')


class EditUser(LoginRequiredMixin, UpdateView):
    model = CustomUser
    form_class = EditUserForm
    template_name = 'user/edit_user.html'
    success_url = reverse_lazy('user:profile_user')
    
    def get_object(self, queryset = None):
        return self.request.user

user/templates/user/edit_user.html
{% extends "base.html" %}

{% block title %}Изменить пользователя{% endblock title %}

{% block content %}
<div class="container">
    <h2>Редактирование профиля</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
</div>
{% endblock %}

user/templates/user/login_user.html
{% extends "base.html" %}

{% block title %}Вход{% endblock title %}

{% block content %}
<div class="container">
    <h2>Вход в систему</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Войти</button>
    </form>
    <p>Нет аккаунта? <a href="{% url 'user:register_user' %}">Зарегистрироваться</a></p>
</div>
{% endblock %}

user/templates/user/profile_user.html
{% extends "base.html" %}

{% block title %}Профиль пользователя{% endblock title %}

{% block content %}
<div class="container">
    <h2>Профиль пользователя: {{ user.username }}</h2>
    
    {% if user.profile_picture %}
        <img src="{{ user.profile_picture.url }}" alt="Аватар" width="150">
    {% else %}
        <p>Аватар отсутствует</p>
    {% endif %}

    <p>Email: {{ user.email }}</p>
    <p>Имя: {{ user.first_name }}</p>
    <p>Фамилия: {{ user.last_name }}</p>

    <a href="{% url 'user:edit_user' %}">Редактировать профиль</a>
</div>
{% endblock %}

user/templates/user/register_user.html
{% extends "base.html" %}

{% block title %}Registration{% endblock title %}

{% block content %}
    <div class="container">
        <h2>Регистрация</h2>
        <form method="post" autocomplete="off">
            {% csrf_token %}

            {% for field in form %}
                <div class="form-group">
                    <label class="form-label">{{ field.label_tag }}</label>
                    <div class="form-input">
                        {{ field }}
                        {% if field.errors %}
                            <div class="alert alert-danger">
                                {{ field.errors.0 }}
                            </div>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
            
            <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
        </form>
    </div>
{% endblock content %}