pingme/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('user/', include('user.urls'))
]

if settings.DEBUG:  # Чтобы медиафайлы работали в режиме отладки
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path

from .views import *

app_name = "tasks"
urlpatterns = [
    path('all_tasks/', AllTasks.as_view(), name='all_tasks'),
    path('task/<slug:slug>/', SingleTask.as_view(), name='single_task'),
    path('create_task/', CreateTask.as_view(), name='create_task'),
    path('edit_task/<slug:slug>/', EditTask.as_view(), name='edit_task'),
    path('delete_task/<slug:slug>/', DeleteTask.as_view(), name='delete_task'),
    # path('complete_task/<int:pk>/', complete_task, name='complete_task'),
]

user/urls.py
from django.urls import path

from .views import *

app_name = "user"

urlpatterns = [
    path('register/', RegisterUser.as_view(), name='register_user'),
    path('profile/',  ProfileUser.as_view(), name='profile_user'),
    path('profile/edit/', EditUser.as_view(), name='edit_user'),
    path('login/', LoginUser.as_view(), name='login_user')
    
]

tasks/models.py
from django.db import models
# from django.utils.text import slugify (Не поддерживает русский язык)
from pytils.translit import slugify # Поддерживает русский язык
from user.models import CustomUser


class Task(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    time_create = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, blank=True, null=True)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    status = models.ForeignKey('Status', on_delete=models.CASCADE)
    is_complete = models.BooleanField(default=False)
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
            n = 1
            while Task.objects.filter(slug=self.slug).exists():
                self.slug = f"{slugify(self.name)}-{n}"
                n+=1
        super().save(*args, **kwargs)
    
    def __str__(self):
        return self.name
    
    
    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'
        ordering = ["-time_create", "is_complete"]
    

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Status(models.Model):

    
    name = models.CharField(max_length=20)
    
    def __str__(self):
        return self.name
    
    
    class Meta:
        verbose_name = 'Статус'
        verbose_name_plural = 'Статусы'

tasks/forms.py
from django import forms
from .models import *

class TaskForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all(), empty_label='Choose category')
    status = forms.ModelChoiceField(queryset=Status.objects.all(), empty_label='Choose  status')
    
    
    class Meta:
        model = Task
        fields =[
            'name',
            'description',
            'category',
            'status',
        ]
        
class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = [
            'name',
        ]
        labels = {
            'name': 'Create category', 
        }

tasks/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.generic import ListView, DetailView, CreateView,  UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import *
from .forms import *
from .utils import get_page_title


class AllTasks(LoginRequiredMixin, ListView):
    
    """
    шаблон есть
    Остались только косметические правки всякие
    Просмотр всех задач 
    Так же можно отметить выполнение задачи (Галочка)
    Обновить статус задачи(Не начата, В процессе, Завершена)
    
    """
    
    model = Task
    template_name = 'tasks/all_tasks.html'
    paginate_by = 10
    context_object_name = 'tasks'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = get_page_title('all_tasks')
        return context
    
    def get_queryset(self):
        return Task.objects.filter(owner=self.request.user).order_by('-time_create')
    
    


class SingleTask(LoginRequiredMixin, DetailView):
    
    """
    
    шаблон есть
    Просмотр атрибутов отдельной задачи:
    Название, описание, сроки и т.д.
    
    """
    
    model = Task
    template_name = 'tasks/single_task.html'
    context_object_name = 'task'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = get_page_title('single_task')
        return context
    


class CreateTask(LoginRequiredMixin, CreateView):
    
    """
    Есть форма для отпраки задачи в БД
    Остались только косметические правки
    Создание задачи:
    Название, описание, сроки и т.д.
    
    """
    
    model = Task
    form_class = TaskForm
    template_name = 'tasks/create_task.html'
    
    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = get_page_title('create_task')
        return context
    
    def get_success_url(self):
        return reverse('tasks:single_task', kwargs={'slug': self.object.slug})

    
    


class EditTask(LoginRequiredMixin, UpdateView):
    
    """
    шаблона нет
    Изменение задачи:
    Названия, описания, сроков и т.д.
    Так же есть возможность удаления задачи 
    При изменении задачи будет перенаправление на просмотр отдельно задачи
    SingleTask(DetailView)
    
    """
    
    model = Task
    form_class = TaskForm
    template_name = 'tasks/edit_task.html'
    
    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = get_page_title('edit_task')
        return context
    
    def get_success_url(self):
        return reverse('tasks:single_task', kwargs={'slug': self.object.slug})
    


class DeleteTask(LoginRequiredMixin, DeleteView):
    model = Task
    template_name ='tasks/delete_task.html'
    
    def get_success_url(self):
        return reverse('tasks:all_tasks')
        


def complete_task(request, pk): 
    tasks = Task.objects.filter(is_complete=True)
    return HttpResponse('')

tasks/templates/tasks/all_tasks.html
{% extends "base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
	<h2>Список задач</h2>
	<ul class='task-list'>
	{% for task in tasks %}
	<li class='task-item'>
	<a href="{% url 'tasks:single_task' slug=task.slug %}">	
		{{ task.name }} | {{ task.status }} | {{ task.category }} | {{ task.is_complete }} 
	</a>
	</li>
	{% endfor %}
	</ul>
{% endblock content %}

tasks/templates/tasks/create_task.html
{% extends "base.html" %}
{% block title %}{{ title }}{% endblock %}

{% block content %}
  <h2>Create New Task</h2>
  
  <!-- Форма для создания задачи -->
  <form method="POST">
    {% csrf_token %}
    
    <!-- Выводим форму -->
    {{ form.as_p }}
    
    <!-- Кнопка для отправки формы -->
    <button type="submit" class="btn btn-danger">Create Task</button>
  </form>
{% endblock %}

tasks/templates/tasks/edit_task.html
{% extends "base.html" %}
{% block title %}{{ title }}{% endblock title %}

{% block content %}
    <h2>Изменение задачи</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <!-- Обработка ошибок -->
        {% if form.errors %} 
        <!-- Если в форме ошибки -->
            <ul class="errors">
                {% for field in form %}
                <!-- Проход по полям форме -->
                    {% for error in field.errors %}
                        <!-- Проваливаемся в field.{errors} -->
                        <li>{{ error }}</li>
                    {% endfor %}
                {% endfor %}
            </ul>
        {% endif %}
        <button type="submit" class="btn btn-success">Сохранить изменения</button>
        
    </form>
    <!-- Кнопка удаления -->
    <form method="POST" action="{% url 'tasks:delete_task' slug=task.slug %}">
            {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить задачу</button>
    </form>
{% endblock content %}

tasks/templates/tasks/single_task.html
{% extends "base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<ul class='task-list'>
    <li>Название: {{task.name}}</li>
    <li>Описание: {{task.description}}</li>
    <li>Время создания: {{task.time_create}}</li>
    <li>Категория: {{task.category.name}}</li>
    <li>Статус: {{task.status.name}}</li>
</ul>
<form method="get" action="{% url "tasks:edit_task" slug=task.slug %}">
    {% csrf_token %}
    <button class="btn btn-success">Редактировать задачу</button>
</form>
{% endblock content %}