pingme/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('user/', include('user.urls'))
]

if settings.DEBUG:  # Чтобы медиафайлы работали в режиме отладки
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path

from .views import *

app_name = "tasks"
urlpatterns = [
    path('all_tasks/', AllTasks.as_view(), name='all_tasks'),
    path('task/<slug:slug>/', SingleTask.as_view(), name='single_task'),
    path('create_task/', CreateTask.as_view(), name='create_task'),
    path('edit_task/<slug:slug>/', EditTask.as_view(), name='edit_task'),
    path('delete_task/<slug:slug>/', DeleteTask.as_view(), name='delete_task'),
    # path('complete_task/<int:pk>/', complete_task, name='complete_task'),
]

user/urls.py
from django.urls import path

from .views import *

app_name = "user"

urlpatterns = [
    path('register/', RegisterUser.as_view(), name='register_user'),
    path('profile/',  ProfileUser.as_view(), name='profile_user'),
    path('profile/edit/', EditUser.as_view(), name='edit_user'),
    path('login/', LoginUser.as_view(), name='login_user')
    
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{{ title }}{% endblock %}</title>
    <link rel="stylesheet" href="{% static "css/styles.css" %}">
</head>
<body>
    <div class='header-container'>
        <nav>
            <ul>
                <li><a href="{% url 'tasks:all_tasks' %}" class="nav-link {% if request.path == '/tasks/all_tasks/' %}active{% endif %}">Все  задачи</a></li>
                <li><a href="{% url 'tasks:create_task' %}" class="nav-link {% if request.path == '/tasks/create_task/' %}active{% endif %}">Создать новую задачу</a></li>
                <li><a href="{% url 'user:profile_user' %}" class="nav-link {% if request.path == '/user/profile/' %}active{% endif %}">Профиль</a></li>
            </ul>
        </nav>
    </div>

    <main>
        {% block content %}
        <!-- Здесь будет содержимое каждой страницы -->
        {% endblock content %}
    </main>
</body>
</html>